"use client";

import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Sparkles, Loader2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import ImageUpload from "@/app/components/image-upload";
import type { UploadedImage } from "@/app/components/image-upload";

type Category = { id: string; name: string; slug: string; icon: string };
type Location = { id: string; name: string; slug: string };

export default function PostClient() {
  const router = useRouter();
  const supabase = createClient();

  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [userId, setUserId] = useState<string | null>(null);
  const [categories, setCategories] = useState<Category[]>([]);
  const [locations, setLocations] = useState<Location[]>([]);
  const [images, setImages] = useState<UploadedImage[]>([]);
  const [formData, setFormData] = useState({
    title: "",
    category_id: "",
    price: "",
    price_type: "fixed",
    description: "",
    condition: "good",
    location_id: "",
  });

  useEffect(() => {
    async function loadData() {
      const [{ data: cats }, { data: locs }, { data: { user } }] = await Promise.all([
        supabase.from("categories").select("id, name, slug, icon").order("sort_order"),
        supabase.from("locations").select("id, name, slug").order("sort_order"),
        supabase.auth.getUser(),
      ]);
      if (cats) setCategories(cats);
      if (locs) setLocations(locs);
      if (user) setUserId(user.id);
    }
    loadData();
  }, []);

  const update = (key: string, value: string) =>
    setFormData((prev) => ({ ...prev, [key]: value }));

  const handleImagesChange = useCallback(
    (newImages: UploadedImage[]) => {
      setImages(newImages);
    },
    [],
  );

  async function handlePublish() {
    setError("");
    setLoading(true);

    if (!userId) {
      router.push("/auth/login?redirect=/post");
      return;
    }

    // Wait for any uploads still in progress
    const pendingUploads = images.some((img) => img.uploading);
    if (pendingUploads) {
      setError("Please wait for all images to finish uploading.");
      setLoading(false);
      return;
    }

    const uploadedUrls = images
      .filter((img) => img.url)
      .map((img) => img.url!);

    const { data, error: insertError } = await supabase
      .from("listings")
      .insert({
        user_id: userId,
        title: formData.title,
        slug: "", // auto-generated by trigger
        category_id: formData.category_id,
        location_id: formData.location_id || null,
        description: formData.description,
        price: formData.price ? Number(formData.price) : null,
        price_type: formData.price_type,
        condition: formData.condition || null,
        status: "active",
        primary_image_url: uploadedUrls[0] || null,
        image_count: uploadedUrls.length,
      })
      .select("id, slug")
      .single();

    if (insertError) {
      setError(insertError.message);
      setLoading(false);
      return;
    }

    // Insert listing images
    if (uploadedUrls.length > 0) {
      const imageRecords = uploadedUrls.map((url, idx) => ({
        listing_id: data.id,
        url,
        sort_order: idx,
      }));
      await supabase.from("listing_images").insert(imageRecords);
    }

    router.push(`/listing/${data.slug}`);
  }

  return (
    <div className="max-w-2xl mx-auto px-4 py-8">
      {/* Progress bar */}
      <div className="flex items-center gap-2 mb-8">
        {[1, 2, 3].map((s) => (
          <div key={s} className="flex-1">
            <div
              className={`h-2 rounded-full transition-colors ${s <= step ? "bg-blue-500" : "bg-gray-200"}`}
            />
          </div>
        ))}
      </div>

      {error && (
        <div className="bg-red-50 text-red-700 text-sm px-4 py-3 rounded-xl border border-red-100 mb-6">
          {error}
        </div>
      )}

      {/* Step 1 — Photos & Title */}
      {step === 1 && (
        <div className="space-y-6">
          <h2 className="text-2xl font-bold text-gray-900">
            What are you selling?
          </h2>

          {/* Image Upload */}
          {userId ? (
            <ImageUpload
              userId={userId}
              images={images}
              onChange={handleImagesChange}
            />
          ) : (
            <div className="border-2 border-dashed border-gray-300 rounded-2xl p-8 text-center bg-white">
              <p className="text-gray-500 text-sm">
                <a href="/auth/login?redirect=/post" className="text-blue-600 font-medium hover:underline">
                  Sign in
                </a>{" "}
                to upload photos
              </p>
            </div>
          )}

          {/* Title */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">
              Title
            </label>
            <input
              type="text"
              className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-400 focus:ring-2 focus:ring-blue-100 outline-none text-sm"
              placeholder="e.g. iPhone 15 Pro Max 256GB Blue"
              value={formData.title}
              onChange={(e) => update("title", e.target.value)}
            />
          </div>

          {/* Category */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">
              Category
            </label>
            <div className="grid grid-cols-4 gap-2">
              {categories.map((cat) => (
                <button
                  key={cat.id}
                  type="button"
                  onClick={() => update("category_id", cat.id)}
                  className={`p-3 rounded-xl border text-center transition-all ${
                    formData.category_id === cat.id
                      ? "border-blue-400 bg-blue-50 ring-2 ring-blue-100"
                      : "border-gray-200 hover:border-gray-300 bg-white"
                  }`}
                >
                  <div className="text-2xl mb-1">{cat.icon}</div>
                  <div className="text-xs font-medium text-gray-700">
                    {cat.name}
                  </div>
                </button>
              ))}
            </div>
          </div>

          <button
            type="button"
            onClick={() => setStep(2)}
            disabled={!formData.title || !formData.category_id}
            className="w-full bg-blue-600 text-white py-3.5 rounded-xl font-semibold hover:bg-blue-700 transition-colors flex items-center justify-center gap-2 disabled:opacity-50"
          >
            Continue <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* Step 2 — Details */}
      {step === 2 && (
        <div className="space-y-6">
          <h2 className="text-2xl font-bold text-gray-900">
            Details &amp; Pricing
          </h2>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">
              Description
            </label>
            <textarea
              className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-400 focus:ring-2 focus:ring-blue-100 outline-none text-sm h-32 resize-none"
              placeholder="Describe your item — condition, features, reason for selling..."
              value={formData.description}
              onChange={(e) => update("description", e.target.value)}
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">
                Price (€)
              </label>
              <div className="relative">
                <span className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 font-medium">
                  €
                </span>
                <input
                  type="number"
                  className="w-full pl-8 pr-4 py-3 rounded-xl border border-gray-200 focus:border-blue-400 focus:ring-2 focus:ring-blue-100 outline-none text-sm"
                  placeholder="0.00"
                  value={formData.price}
                  onChange={(e) => update("price", e.target.value)}
                />
              </div>
              {formData.price && (
                <div className="flex items-center gap-1.5 mt-2 text-xs text-green-600 bg-green-50 px-2.5 py-1.5 rounded-lg">
                  <Sparkles className="w-3 h-3" />
                  Similar items sell for €
                  {Math.round(Number(formData.price) * 0.9)} – €
                  {Math.round(Number(formData.price) * 1.1)}
                </div>
              )}
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">
                Condition
              </label>
              <select
                className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-400 focus:ring-2 focus:ring-blue-100 outline-none text-sm bg-white"
                value={formData.condition}
                onChange={(e) => update("condition", e.target.value)}
              >
                <option value="new">New</option>
                <option value="like_new">Like New</option>
                <option value="good">Good</option>
                <option value="fair">Fair</option>
                <option value="for_parts">For Parts</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">
                Location
              </label>
              <select
                className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-400 focus:ring-2 focus:ring-blue-100 outline-none text-sm bg-white"
                value={formData.location_id}
                onChange={(e) => update("location_id", e.target.value)}
              >
                <option value="">Select location</option>
                {locations.map((loc) => (
                  <option key={loc.id} value={loc.id}>
                    {loc.name}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">
                Price Type
              </label>
              <select
                className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-400 focus:ring-2 focus:ring-blue-100 outline-none text-sm bg-white"
                value={formData.price_type}
                onChange={(e) => update("price_type", e.target.value)}
              >
                <option value="fixed">Fixed Price</option>
                <option value="negotiable">Negotiable</option>
                <option value="free">Free</option>
                <option value="contact">Contact for Price</option>
              </select>
            </div>
          </div>

          <div className="flex gap-3">
            <button
              type="button"
              onClick={() => setStep(1)}
              className="flex-1 bg-gray-100 text-gray-700 py-3.5 rounded-xl font-semibold hover:bg-gray-200 transition-colors flex items-center justify-center gap-2"
            >
              <ArrowLeft className="w-4 h-4" /> Back
            </button>
            <button
              type="button"
              onClick={() => setStep(3)}
              className="flex-1 bg-blue-600 text-white py-3.5 rounded-xl font-semibold hover:bg-blue-700 transition-colors flex items-center justify-center gap-2"
            >
              Continue <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* Step 3 — Boost & Publish */}
      {step === 3 && (
        <div className="space-y-6">
          <h2 className="text-2xl font-bold text-gray-900">
            Boost Your Listing
          </h2>

          {/* Preview summary */}
          <div className="bg-white rounded-xl border border-gray-100 p-5">
            <h3 className="text-sm font-medium text-gray-500 mb-3">Preview</h3>
            <div className="flex gap-4">
              {images[0] && (
                <div className="w-20 h-20 rounded-lg overflow-hidden flex-shrink-0 bg-gray-100">
                  <img
                    src={images[0].preview}
                    alt=""
                    className="w-full h-full object-cover"
                  />
                </div>
              )}
              <div>
                <p className="font-semibold text-gray-900">{formData.title}</p>
                <p className="text-sm text-gray-500 mt-0.5">
                  {formData.price ? `€${Number(formData.price).toLocaleString()}` : "Contact for price"}
                  {" · "}
                  {images.length} photo{images.length !== 1 ? "s" : ""}
                </p>
              </div>
            </div>
          </div>

          <div className="space-y-3">
            <div className="bg-white border-2 border-blue-400 rounded-xl p-5 cursor-pointer ring-2 ring-blue-100">
              <div className="flex items-center justify-between">
                <div>
                  <div className="font-semibold text-gray-900">
                    Free Listing
                  </div>
                  <div className="text-sm text-gray-500">
                    Standard visibility for 30 days
                  </div>
                </div>
                <div className="font-bold text-gray-900">Free</div>
              </div>
            </div>

            <div className="bg-gradient-to-r from-amber-50 to-orange-50 border-2 border-amber-300 rounded-xl p-5 cursor-pointer relative opacity-80">
              <div className="absolute -top-2.5 right-4 bg-amber-500 text-white text-xs font-bold px-2.5 py-0.5 rounded-full">
                POPULAR
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <div className="font-semibold text-gray-900">
                    Featured Listing
                  </div>
                  <div className="text-sm text-gray-500">
                    Top placement + highlighted for 7 days
                  </div>
                </div>
                <div className="font-bold text-amber-600">€4.99</div>
              </div>
            </div>

            <div className="bg-white border border-gray-200 rounded-xl p-5 cursor-pointer opacity-80">
              <div className="flex items-center justify-between">
                <div>
                  <div className="font-semibold text-gray-900">
                    Urgent Badge
                  </div>
                  <div className="text-sm text-gray-500">
                    Urgent badge + priority in search for 3 days
                  </div>
                </div>
                <div className="font-bold text-gray-900">€2.99</div>
              </div>
            </div>
          </div>

          <div className="flex gap-3">
            <button
              type="button"
              onClick={() => setStep(2)}
              className="flex-1 bg-gray-100 text-gray-700 py-3.5 rounded-xl font-semibold hover:bg-gray-200 transition-colors flex items-center justify-center gap-2"
            >
              <ArrowLeft className="w-4 h-4" /> Back
            </button>
            <button
              type="button"
              onClick={handlePublish}
              disabled={loading}
              className="flex-1 bg-green-600 text-white py-3.5 rounded-xl font-semibold hover:bg-green-700 transition-colors flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {loading ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                "Publish Listing"
              )}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
